<?php

namespace AppBundle\Repository;

/**
 * AccordPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccordPermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
