<?php

namespace AppBundle\Repository;

/**
 * CompteComptaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteComptaRepository extends \Doctrine\ORM\EntityRepository
{
}
