<?php

namespace AppBundle\Repository;

/**
 * DemandePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandePermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
