<?php

namespace AppBundle\Repository;

/**
 * ImportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportationRepository extends \Doctrine\ORM\EntityRepository
{
}
