<?php

namespace AppBundle\Repository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends \Doctrine\ORM\EntityRepository
{
}
