<?php

namespace AppBundle\Repository;

/**
 * OperationCaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationCaisseRepository extends \Doctrine\ORM\EntityRepository
{
	public function getStat($id)
    {
        $query="
        SELECT o.dateDeReglement as dateReglement , SUM(o.prime) as prime, c.num as numeroCompteDebit
        FROM AppBundle:OperationCaisse o, AppBundle:TypeOperation t,AppBundle:Importation i,AppBundle:CompteCompta c  
        WHERE i.typeOperation=t.id and o.importation =i.id and c =t.compteCompta and i.id='$id'
        GROUP BY o.dateDeReglement ";
        return $this->getEntityManager()->createQuery($query)->getResult();
    }

    public function cumul($id)
    {
        $query="
        SELECT  SUM(o.prime) as prime, c.num as numeroCompteDebit, t.libelleTypeOperation as type, o.dateDeReglement as dateReglement
        FROM AppBundle:OperationCaisse o, AppBundle:TypeOperation t,AppBundle:Importation i ,AppBundle:CompteCompta c
        WHERE i.typeOperation=t.id and o.importation =i.id and c =t.compteCompta  and i.id='$id'
        GROUP BY o.dateDeReglement ";
        return $this->getEntityManager()->createQuery($query)->getResult();
    }

}




