<?php

namespace AppBundle\Repository;

/**
 * TypeOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
