<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjrpak1\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjrpak1/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXjrpak1.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXjrpak1\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXjrpak1\appProdProjectContainer([
    'container.build_hash' => 'Xjrpak1',
    'container.build_id' => 'a53b1c41',
    'container.build_time' => 1555414307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjrpak1');
