<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBo0kecu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBo0kecu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBo0kecu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBo0kecu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBo0kecu\appProdProjectContainer([
    'container.build_hash' => 'Bo0kecu',
    'container.build_id' => '9cda32e5',
    'container.build_time' => 1555320099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBo0kecu');
