<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLo8zieu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLo8zieu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLo8zieu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLo8zieu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLo8zieu\appDevDebugProjectContainer([
    'container.build_hash' => 'Lo8zieu',
    'container.build_id' => '8bc6de31',
    'container.build_time' => 1555345694,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLo8zieu');
