<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMkddy2t\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMkddy2t/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMkddy2t.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMkddy2t\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMkddy2t\appDevDebugProjectContainer([
    'container.build_hash' => 'Mkddy2t',
    'container.build_id' => '5a0d4d87',
    'container.build_time' => 1555433312,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMkddy2t');
