<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5cuihb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5cuihb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerA5cuihb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerA5cuihb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerA5cuihb\appDevDebugProjectContainer([
    'container.build_hash' => 'A5cuihb',
    'container.build_id' => '5a4e9685',
    'container.build_time' => 1555414287,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5cuihb');
