<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \AppBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'nomProduit', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'numeroDeCodeProduit', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'numCptCredit', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'operations'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'nomProduit', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'numeroDeCodeProduit', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'numCptCredit', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'operations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProduit($nomProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProduit', [$nomProduit]);

        return parent::setNomProduit($nomProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProduit', []);

        return parent::getNomProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function getOperations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperations', []);

        return parent::getOperations();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperations($operations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperations', [$operations]);

        return parent::setOperations($operations);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDeCodeProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDeCodeProduit', []);

        return parent::getNumeroDeCodeProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDeCodeProduit($numeroDeCodeProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDeCodeProduit', [$numeroDeCodeProduit]);

        return parent::setNumeroDeCodeProduit($numeroDeCodeProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumCptCredit($numCptCredit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumCptCredit', [$numCptCredit]);

        return parent::setNumCptCredit($numCptCredit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumCptCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumCptCredit', []);

        return parent::getNumCptCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperation(\AppBundle\Entity\OperationCaisse $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperation', [$operation]);

        return parent::addOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperation(\AppBundle\Entity\OperationCaisse $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperation', [$operation]);

        return parent::removeOperation($operation);
    }

}
